apiVersion: argoproj.io/v1alpha
kind: Application
metadata: 
  name: devops-toolkit
  namespace: argocd
  finalizers: 
    - resources-finalizer.argocd.argoproj.io

spec: 
  project: default
  source: 
    path: helm
    repoURL: https://github.com/vfarcic/devops-toolkit.git
    targetRevision: HEAD
    helm: 
      values: |
        image: 
          tag: latest
        ingress: 
          host: devops-toolkit.192.168.64.14.xip.io
      versions: v3
  destination: 
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy: 
    automated: 
      selfHeal: true
      prune: true 